### ISSUE TITLE
Efficient Linear Layer

### ISSUE THREAD

**Issue by kayuksel** [BayesWatch/deficient-efficient#1]
Dear Gavin,

I am trying to find an efficient linear layer. I have read that discrete cosine transform is helpful in reducing the dimensionality. 

I have tried your ACDC layer implementation in your other repository. But, the process gets killed with that for some reason.

As I understood from your publication, there are several methods in this repository but most of them are for 2D convolutions. 

Do you have any such efficient Linear layer here that I can also try using it? Thank you very much in advance. Sincerely, KY

**Comment by gngdb** [comment]
I'm sorry the ACDC implementation from the other repository is out of date. Recently, Pytorch added [support for FFTs][fft] and it would be possible to write a much more efficient DCT and ACDC layer using those. In many of the experiments in this repository I'm using a fixed DCT matrix in lieu of an FFT algorithm, which is not efficient but performs the same function.

Any 2D Convolution with a kernel size of `(1,1)` can be used as a Linear layer if you add height and width dimensions of size 1, like for example in pseudocode:

```
> x.size()
(batch_size, dim)
> x = x.view(batch_size, dim, 1, 1)
> y = conv2d(x) # this conv2d must have kernel size of (1,1)
> y = y.size()
(batch_size, out_channels, 1, 1)
> y = y.squeeze()
> y.size()
(batch_size, out_channels)
```

Any of the 2D convolutional layers will work in this way. I think the simplest and best for most real application is the [Linearised ShuffleNet block](https://github.com/BayesWatch/deficient-efficient/blob/master/models/blocks.py#L119-L155).

[fft]: https://pytorch.org/blog/the-torch.fft-module-accelerated-fast-fourier-transforms-with-autograd-in-pyTorch/
